### ISSUE TITLE
Privacy manifest contains incorrect values

### ISSUE THREAD

**Issue by hedgehogowainbrown** [forcedotcom/SalesforceMobileSDK-iOS-SPM#2]
When importing this SDK via SPM, the privacy manifest contains invalid (empty) values, and causes a binary to be rejected from the app store.

> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/SalesforceSDKCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

I note a fix is present in develop in the main repository.  Can that be imported to this repo for use in SPM?

I also note the minimum iOS versions appear inconsistent.  Via SPM, the minimum appears to be iOS 15.  If imported individually as cocoapods, the SalesforceSDKCommon has a minimum iOS version of 16.0.  Could you please confirm which is correct?

**Comment by ryang1428** [comment]
Yes we also are blocked from releasing a critical hot fix because of this!

**Comment by ryang1428** [comment]
@bbirman for awareness (I saw you attached to the recent PR)

**Comment by bbirman** [comment]
We're working on a patch for this issue. @hedgehogowainbrown thanks for reporting the deployment mismatch as well, the correct one is 16.0, we'll update that too

**Comment by ryang1428** [comment]
@bbirman any rough timelines on this? Again we are blocked from releasing a crash fix 😢

**Comment by bbirman** [comment]
We're planning on Monday

**Comment by bbirman** [comment]
Mobile SDK 12.0.1 has been released with the fix
